export enum PERMISSIONS {
    ADD_BRANCH = 'ADD_BRANCH',
    EDIT_BRANCH = 'EDIT_BRANCH',
    DELETE_BRANCH = 'DELETE_BRANCH',

    ADD_HCF = 'ADD_HCF',
    EDIT_HCF = 'EDIT_HCF',
    DELETE_HCF = 'DELETE_HCF',

    ADD_PHARMACY = 'ADD_PHARMACY',
    EDIT_PHARMACY = 'EDIT_PHARMACY',
    DELETE_PHARMACY = 'DELETE_PHARMACY',

    ADD_DRUG = 'ADD_DRUG',
    EDIT_DRUG = 'EDIT_DRUG',
    DELETE_DRUG = 'DELETE_DRUG',
    //
    ADD_USER = 'ADD_USER',
    EDIT_USER = 'EDIT_USER',
    FIRED_USER = 'FIRED_USER',

    ADD_AGENT = 'ADD_AGENT',
    EDIT_AGENT = 'EDIT_AGENT',
    DELETE_AGENT = 'DELETE_AGENT',
    //
    EDIT_SALARY = 'EDIT_SALARY',
    SEE_REPORT = 'SEE_REPORT',
}
