export enum USER_ROLE {
    UNKNOWN,
    ADMIN = 1,
    FIELD_FORCE_MANAGER,
    REGIONAL_MANAGER,
    MEDICAL_AGENT,
    SUPER_ADMIN,
    PRODUCT_MANAGER
}

export const singleDepartmentRoles: USER_ROLE[] = [
    USER_ROLE.MEDICAL_AGENT,
    USER_ROLE.REGIONAL_MANAGER,
    USER_ROLE.FIELD_FORCE_MANAGER,
];

export const multiDepartmentRoles: USER_ROLE[] = [
    USER_ROLE.PRODUCT_MANAGER,
    USER_ROLE.ADMIN,
    USER_ROLE.SUPER_ADMIN
];
